//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PicishLexer.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public partial class PicishLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BOX=1, LINE=2, SEMI=3, WS=4;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"BOX", "LINE", "SEMI", "WS"
	};


	public PicishLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PicishLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'box'", "'line'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BOX", "LINE", "SEMI", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PicishLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static PicishLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x6', '\x1D', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x6', '\x5', '\x18', '\n', '\x5', 
		'\r', '\x5', '\xE', '\x5', '\x19', '\x3', '\x5', '\x3', '\x5', '\x2', 
		'\x2', '\x6', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\x3', 
		'\x2', '\x3', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', 
		'\x1D', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\v', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\a', '\x14', '\x3', '\x2', '\x2', 
		'\x2', '\t', '\x17', '\x3', '\x2', '\x2', '\x2', '\v', '\f', '\a', '\x64', 
		'\x2', '\x2', '\f', '\r', '\a', 'q', '\x2', '\x2', '\r', '\xE', '\a', 
		'z', '\x2', '\x2', '\xE', '\x4', '\x3', '\x2', '\x2', '\x2', '\xF', '\x10', 
		'\a', 'n', '\x2', '\x2', '\x10', '\x11', '\a', 'k', '\x2', '\x2', '\x11', 
		'\x12', '\a', 'p', '\x2', '\x2', '\x12', '\x13', '\a', 'g', '\x2', '\x2', 
		'\x13', '\x6', '\x3', '\x2', '\x2', '\x2', '\x14', '\x15', '\a', '=', 
		'\x2', '\x2', '\x15', '\b', '\x3', '\x2', '\x2', '\x2', '\x16', '\x18', 
		'\t', '\x2', '\x2', '\x2', '\x17', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'\x18', '\x19', '\x3', '\x2', '\x2', '\x2', '\x19', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x1B', '\x1C', '\b', '\x5', '\x2', '\x2', 
		'\x1C', '\n', '\x3', '\x2', '\x2', '\x2', '\x4', '\x2', '\x19', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
